### ISSUE TITLE
how can we write the raw sql query in repository 

### ISSUE THREAD

**Issue by skanel** [paulushcgcj/multidbspring#1]
how can we write the raw sql query in repository ?

**Comment by paulushcgcj** [comment]
Hi @skanel
As the code uses spring-data, you can use the same approach as you usually do, by creating a signature on repository interface and annotating it with `@Query`.

There is a great article at [Baeldung](https://www.baeldung.com/spring-data-jpa-query) describing it, you can check it out.

If you are worried about running both queries at different databases due to a possible mismatch... I'm afraid you will have to have both tables with the same fields you want to consume in your query.

Hope this helped you,
Have a nice day

**Comment by paulushcgcj** [comment]
Closing the issue due to lack of response.
